### ISSUE TITLE
How can I download those paper?

### ISSUE THREAD

**Issue by wbzhang233** [PaoPaoRobot/IROS2019-paper-list#1]
请问上哪儿下载呢？能否给一个链接？Baidu网盘链接最好了，国内梯子有点儿高，小萌新求指点呀。

**Comment by yvonshong** [comment]
Baidu 网盘链接不方便维护，经常会失效。可以根据 paper 标题搜 DOI 编码，然后在https://sci-hub.tw/ 根据 DOI 编码下载。
